---
# For Mac OSX env
# See: https://github.com/ansible/ansible-modules-core/issues/4246
# Don't forget add ansible_python_interpreter=/usr/local/Cellar/python@2/2.7.14_3/bin/python in inventory
- name: install docker-py
  command: pip install docker-py

- name: pull docker images
  docker_image:
    name: "{{ item.split(':')[0] }}"
    tag: "{{ item.split(':')[1] }}"
    force: yes
  with_items: "{{ images }}"

- name: archive images
  docker_image:
    name: "{{ item.split(':')[0] }}"
    tag: "{{ item.split(':')[1] }}"
    force: yes
    archive_path: images/{{ item | basename }}.tar
  with_items: "{{ images }}"

- name: print image list
  debug:
    var: images
