---
- name: helm set up just a local environment
  command: helm init -c

- name: helm add a chart repository
  command: helm repo add {{ chart_repo_name }} {{ location }}

- name: update information of available charts locally from chart repositories
  command: helm repo up
