---
- name: configure dynamic linker run time bindings
  lineinfile:
    path: /etc/ld.so.conf
    line: /usr/local/lib
  register: result

- name: ldconfig
  command: ldconfig
  when: result.changed

- name: download libgit2
  unarchive:
    src: "{{ libgit2_url }}"
    dest: /tmp
    copy: no

- name: install libgit2
  command: "{{ item }}"
  args:
    chdir: "/tmp/libgit2-{{ libgit2_version }}"
  with_items:
    - cmake .
    - make
    - make install
