---
- name: upgrade special modules
  pip:
    name: "{{ item }}"
    extra_args: -U -I
  with_items:
    - requests
    - pyyaml

- name: configure dynamic linker run time bindings
  lineinfile:
    path: /etc/ld.so.conf
    line: /usr/local/lib

- name: download libgit2
  unarchive:
    src: "{{ libgit2_url }}"
    dest: /tmp
    copy: no

- name: install libgit2
  command: "{{ item }}"
  args:
    chdir: "/tmp/libgit2-{{ libgit2_version }}"
  with_items:
    - cmake .
    - make
    - make install

- name: ldconfig
  command: ldconfig
