- name: get Tiller's server host
  command: "kubectl get svc -n kube-system tiller-deploy -o jsonpath='{.spec.clusterIP}'"
  register: tiller_host

- name: delete helm release projects
  helm:
    host: "{{ tiller_host.stdout }}"
    state: purged
    name: "{{ item.release }}-{{ deploy_customer }}"
  with_items: "{{ deploy_proj }}"
  ignore_errors: True

- name: delete namespace
  shell: kubectl delete namespace {{ deploy_customer }}
