---
- name: create helm_pkgs directory
  file:
    path: helm_pkgs
    state: directory

- name: retrieve packages
  command: helm fetch {{ chart_repo_name }}/{{ item.chart }} --version {{ item.version }} -d helm_pkgs
  with_items: "{{ projects }}"
