---
- name: include distro vars
  include_vars: "{{ ansible_distribution }}.yml"

- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: "ansible_distribution == 'Ubuntu'"

- name: install essential packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ pkgs_lists }}"
